### ISSUE TITLE
This is great! Any plans to add support for links and anchor tags?

### ISSUE THREAD

**Issue by mbelkin** [nicolasgoutaland/GONMarkupParser#1]

**Comment by nicolasgoutaland** [comment]
Hi,
Can you give me more  information and an example ?
Thanks for your interest ;)

**Comment by mbelkin** [comment]
For example, to process a string like: `You can <a href="http://google.com">tap here</a> to search Google`. Recognizing and embedding that link would be really helpful.

**Comment by nicolasgoutaland** [comment]
Ok, I see.
Currently, GONMarkupParser is intended only to generate NSAttributedString.
The best way to achieve this, is to create a new markup, handling <a>.
Using this markup, so can update the string to add a hidden link (Using backspace UTF-8 character).
Then, you will have to subclass a UITextView to handle touches, and detect link.
I have developped a component doing this, for personnal use.
I will check if I can clean it to match this use case.

**Comment by timonus** [comment]
I would love this too!

**Comment by nicolasgoutaland** [comment]
OK, working on it.

**Comment by nicolasgoutaland** [comment]
Hi guys,
Just pushed a develop branch with a support for link markup.
https://github.com/nicolasgoutaland/GONMarkupParser/tree/develop

```
<link value="http://www.google.com">Link to google</>
```

If you want a callback when user click on link, display AttributedString in a UITextView, and implements following delegate method 

```
#pragma mark - UITextViewDelegate methods
- (BOOL)textView:(UITextView *)textView shouldInteractWithTextAttachment:(NSTextAttachment *)textAttachment inRange:(NSRange)characterRange
{
    NSString *attachementValue = [[NSString alloc] initWithData:textAttachment.contents
                                                       encoding:NSUTF8StringEncoding];

    // Show link value
    UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Information"
                                                    message:attachementValue
                                                   delegate:nil
                                          cancelButtonTitle:@"OK"
                                          otherButtonTitles:nil];
    [alert show];

    return NO;
}
```

UITextView should be selectable but not editable for this delegate method to be called.

To customize link attributes, you have to use **linkTextAttributes** property

Let me know if its ok for you.

**Comment by timonus** [comment]
Cool, I think you should support anchor tags in addition to link tags. So

```
<a href="http://www.hello.com">Hello World</a>
```

Should work.

**Comment by nicolasgoutaland** [comment]
Ok. I did rename it  to "a href", to be more HTML like ;)
Let me know is everything is ok for you.

**Comment by timonus** [comment]
I've actually decided to go with another solution, I wrote my own small HTML-to-NSAttributedString parser on top of libxml. I think adopting anchor tags would still be a good thing for your library to support though.

**Comment by nicolasgoutaland** [comment]
Hi, done in last release ;)
