### ISSUE TITLE
<p> is not getting replaced 

### ISSUE THREAD

**Issue by pranavpari** [nicolasgoutaland/GONMarkupParser#14]
Hello, I am trying a following code but still I am getting`<p>`in my label text

```
let parser = GONMarkupParser.defaultMarkupParser()
parser.replaceNewLineCharactersFromInputString = true
parser.attributedStringFromString(html)
```

**Comment by nicolasgoutaland** [comment]
Hi,
Can you paste the input string your are trying to convert ?
Regards,

**Comment by pranavpari** [comment]
```
<p>Yummy homemade Jam bursting with fruity goodness,&nbsp;fresh
Qishta/Labneh accompanied by fresh tandoor baked bread.<br
/>\r\n<span style="line-height: 1.6em;">Add BD
1&nbsp;to get Extra
Goodies.</span></p>\r\n\r\n<p>&nbsp;</p>\r\n

```

On Fri, Apr 15, 2016 at 9:52 PM, Nicolas Goutaland <notifications@github.com

> wrote:
> 
> Hi,
> Can you paste the input string your are trying to convert ?
> Regards,
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nicolasgoutaland/GONMarkupParser/issues/14#issuecomment-210528567

## 

_Thanks & Regards,_

_Pranav Goswami.Mo: +91 8000 672 007_
_Website: pranavgoswami.com http://pranavgoswami.com_
_Skype:pranav_goswami01_

**Comment by nicolasgoutaland** [comment]
Can you past me a picture of the output ?
Regards

**Comment by pranavpari** [comment]
I solved it by doing second time decoding.

Thanks for the help

On Wed, Apr 20, 2016 at 7:43 PM, Nicolas Goutaland <notifications@github.com

> wrote:
> 
> Can you past me a picture of the output ?
> Regards
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/nicolasgoutaland/GONMarkupParser/issues/14#issuecomment-212442434

## 

_Thanks & Regards,_

_Pranav Goswami.Mo: +91 8000 672 007_
_Website: pranavgoswami.com http://pranavgoswami.com_
_Skype:pranav_goswami01_
