### ISSUE TITLE
I can't compile with this libaray.

### ISSUE THREAD

**Issue by Ying1986** [nicolasgoutaland/GONMarkupParser#15]
I have added this library, but I can' compile it as following error log.

`/.../Pods/GONMarkupParser/Classes/GONMarkupColor.m:10:9: 'NSString+Color/NSString+Color.h' file not found`

I'm using Cocoapods 1.0.

**Comment by nicolasgoutaland** [comment]
Hi,
Sorry to here that. How did you declare the library in your podfile.
Regards,

**Comment by Ying1986** [comment]
I put as `pod 'GONMarkupParser'`.

**Comment by Ying1986** [comment]
@nicolasgoutaland 

I pus as following:

platform :ios, 9.0

abstract_target '..'

pod 'GONMarkupParser' 

target 'target1' do
use_frameworks!
end

target 'target2' do
use_frameworks!
end
...

**Comment by nicolasgoutaland** [comment]
Is your compilation problem solved ? Because you have opened an other ticket explaining you have compiled the library ?

**Comment by Ying1986** [comment]
No, I can't compile, yet.

You can test it by adding your library to empty swift project.

**Comment by nicolasgoutaland** [comment]
Ok I see. This is due to last fix in #9 

I will update the library to reflect changes in Cocoapods 1.0.0.

Thanks for your feedback

**Comment by nicolasgoutaland** [comment]
Hi, did just pushed a new branch, develop-15. Can you try to install pod from it ?

Juste update 

```
pod 'GONMarkupParser'
```

to 

```
pod 'GONMarkupParser', :git => 'https://github.com/nicolasgoutaland/GONMarkupParser.git', :branch => 'develop-15'

```

**Comment by Ying1986** [comment]
your new branch looks good.

**Comment by nicolasgoutaland** [comment]
Ok, great, I will publish an updated pod version

**Comment by Ying1986** [comment]
But I think you did set pod with 0.39.

Please check the last line of `Example/Podfile.lock` from https://github.com/nicolasgoutaland/GONMarkupParser/commit/312d62a8ac6105d7ef6fcb0d3a3edc2cfcbe616e..

**Comment by nicolasgoutaland** [comment]
Yes, I did try with cocoapods 1.0.0 first, then pushed after a try with 0.39, current version I am working with.

**Comment by Ying1986** [comment]
Did you push the changes for this issue to `master`?

**Comment by nicolasgoutaland** [comment]
Not yet

**Comment by nicolasgoutaland** [comment]
Hi, did just push 0.7.0.
Let me know if everything is ok for you now.
Regards

**Comment by nicolasgoutaland** [comment]
Hi, can I assume this problem solved and close the issue ?
