### ISSUE TITLE
There is the different appearance.

### ISSUE THREAD

**Issue by Ying1986** [nicolasgoutaland/GONMarkupParser#16]
When html body is 
`<div>a</div>
<div>b</div>`
it appears **a\nb** (two line) on web browser, but in your library it is appear one line string **ab**,

**Comment by nicolasgoutaland** [comment]
Hi, 
you have a parameter, **_replaceNewLineCharactersFromInputString**_ in **GONMarkupParser** class allowing you to ignore new line characters in your text. Set it to **YES**, so only &lt;br/&gt; and &lt;p&gt; will generate new line characters, like in pur HTML.

Let me know if it solves your problem.

Regards

**Comment by Ying1986** [comment]
I'm talking about subsequence of **`<div>`** array.
On web browser it appear as multi lines (one div appears as one paragraph), but in your library it appear one line.

> My html string has many `<div>` tags while edit rich editor by using https://github.com/cjwirth/RichEditorView.

**Comment by nicolasgoutaland** [comment]
Ok. I see. Div isn't natively supported by the library. Its purpose is not to display pur HTML, but to simplfy attributedString generation.
The simplier way is to add a block markup :

```
    #import "GONMarkupList.h"
```

```
    // Custom markup, based on block
    GONMarkupBlock *markupBlock = [GONMarkupBlock blockMarkup:@"div"];
    markupBlock.updatedContentStringBlock = ^(NSString *string, NSMutableDictionary *context, NSDictionary *dicAttributes, NSDictionary *stringAttributes) {
        // If in a list, no new lines
        if ([context objectForKey:GONMarkupList_CONFIGURATIONS_KEY])
            return [[NSAttributedString alloc] initWithString:@"\u2028" attributes:stringAttributes];

            return [[NSAttributedString alloc] initWithString:@"\n" attributes:stringAttributes];
    };

    [_parser addMarkup:markupBlock];
```

**Comment by Ying1986** [comment]
I can't see anything after add above code.

**Comment by nicolasgoutaland** [comment]
Ok I see.
I didn't understood you problem.
Please try with this :

```
  // Custom markup, based on block
    GONMarkupBlock *markupBlock = [GONMarkupBlock blockMarkup:@"div"];
    markupBlock.suffixStringForContextBlock = ^(NSMutableDictionary *context, NSDictionary *dicAttributes, NSDictionary *stringAttributes) {
        // If in a list, no new lines
        if ([context objectForKey:GONMarkupList_CONFIGURATIONS_KEY])
            return [[NSAttributedString alloc] initWithString:@"\u2028" attributes:stringAttributes];

     return [[NSAttributedString alloc] initWithString:@"\n" attributes:stringAttributes];
    };

    [_parser addMarkup:markupBlock];
```

This will add a suffix instead of replacing content.

Regards

**Comment by Ying1986** [comment]
After use above `_parse` there is no any character in UILabel,

Why did you return `\n`? 
Perhaps `<div>\n + content <\dev>`???
