### ISSUE TITLE
How to support image from remote-service?

### ISSUE THREAD

**Issue by cloudhm** [nicolasgoutaland/GONMarkupParser#17]
How to support image from remote-service?
`<img src="http://h.hiphotos.baidu.com/image/h%3D200/sign=e72c850a09f3d7ca13f63876c21fbe3c/a2cc7cd98d1001e9460fd63bbd0e7bec54e797d7.jpg" />`

**Comment by nicolasgoutaland** [comment]
Hi,
There is currently no way to load remote images.
I was working on a feature allowing to display images, but only local one will be supported.
Regards

**Comment by rockingdice** [comment]
@nicolasgoutaland any ETA for local images? looking forward to it :)
