### ISSUE TITLE
Method accepting NSError** should have a non-void return value to indicate whether or not an error occurred warnings

### ISSUE THREAD

**Issue by MichaelKelly98** [nicolasgoutaland/GONMarkupParser#18]
LLVM/Clang warnings when compiling due to methods that accept NSError*\* not returning a BOOL value to indicate if there was an error.

File with error: GONMarkupParser.m

Methods with error: 
- (void)handleClosingTag:(NSString _)tag error:(NSError *_)error (line 426)
- (void)handleOpeningTag:(NSString _)tag error:(NSError *_)error (line 504)
- (void)generateError:(NSError **)error tag:(NSString *)tag (line 567)

Don't mind creating a PR if requested.

**Comment by nicolasgoutaland** [comment]
That's a good point. I should totally update these methods signature.
Thanks.

**Comment by MichaelKelly98** [comment]
Sounds good, thank you for your quick reply.

**Comment by nicolasgoutaland** [comment]
Thanks to you, I was able to fix a bug ;)
