### ISSUE TITLE
Parsing tag with attribute

### ISSUE THREAD

**Issue by bergerjohannes** [nicolasgoutaland/GONMarkupParser#20]
I try to parse `<span class="keyword">` and `<span class="string">`.
This is my setup: 
`[[GONMarkupParserManager sharedParser] addMarkup:[GONMarkupSimple simpleMarkup:@"<span class=\"string\">" style:@{  NSFontAttributeName: [UIFont fontWithName:@"Menlo-Regular" size:fontSize], NSForegroundColorAttributeName: [UIColor redColor] } mergingStrategy:GONMarkupSimpleMergingStrategyMergeAll]];`

I've also tried:
`[[GONMarkupParserManager sharedParser] addMarkup:[GONMarkupSimple simpleMarkup:@"span class=\"string\"" style:@{  NSFontAttributeName: [UIFont fontWithName:@"Menlo-Regular" size:fontSize], NSForegroundColorAttributeName: [UIColor redColor] } mergingStrategy:GONMarkupSimpleMergingStrategyMergeAll]];`

In both cases, I receive **MarkupParser : No markup found for tag <span>**. Of course, I can add `span` as a tag, but I need to differentiate strings and keywords.

Do you have a solution for this problem?

Btw: Great parser! 🙌

**Comment by nicolasgoutaland** [comment]
Hi !
In fact, the markup name have to be only the tag, without &lt; and &gt; or attributes.
So, as you should have guessed, you cannot achieve this by using a **GONMarkupSimple**.
But, you are a lucky guy, let me introduce you the [**GONMarkupBlock**](https://github.com/nicolasgoutaland/GONMarkupParser#adding-a-new-block-based-marker).
Create one, and update style base on attributes.

```
   // Retrieve shared parser
    GONMarkupParser *parser = [GONMarkupParserManager sharedParser];

    // Custom markup, based on block
    GONMarkupBlock *markupBlock = [GONMarkupBlock blockMarkup:@"custom"];
    markupBlock.openingMarkupBlock = ^(NSMutableDictionary *configurationDictionary, NSString *tag, NSMutableDictionary *context, NSDictionary *attributes) {
        CGFloat fontSize = 12.0;
        NSString *className = [attributes objectForKey:@"class"];
        if ([className isEqualToString:@"keyword"])
        {
            [configurationDictionary addEntriesFromDictionary:@{
                                                                NSFontAttributeName: [UIFont fontWithName:@"Menlo-Regular" size:fontSize],
                                                                NSForegroundColorAttributeName: [UIColor redColor]
                                                                }];
        }

        if ([className isEqualToString:@"string"])
        {
            [configurationDictionary addEntriesFromDictionary:@{
                                                                    NSFontAttributeName: [UIFont fontWithName:@"Menlo-Regular" size:fontSize],
                                                                    NSForegroundColorAttributeName: [UIColor whiteColor]
                                                                }];
        }
    };

    [parser addMarkup:markupBlock];
```

Let me know if it's good for you ;)

**Comment by bergerjohannes** [comment]
Thank you very much! That's exactly what I needed. Closing issue.
