### ISSUE TITLE
Code crashes on certain invalid HTML string

### ISSUE THREAD

**Issue by krzysztof-grobelny** [nicolasgoutaland/GONMarkupParser#21]
The code crashes when attempting to parse the following string:
`@"<br>><<body>This is expected string<font color=\">Color</xxxx></body><"
`

I know it is invalid, but it should recover gracefully.
Error thrown:

> caught "NSRangeException", "**\* -[__NSCFConstantString substringToIndex:]: Index 18446744073709551615 out of bounds; string length 0"

**Comment by nicolasgoutaland** [comment]
Shame on me, I will fix it ;)

**Comment by krzysztof-grobelny** [comment]
Sorry, just spotted it and had no time yet to contribute.
Depends on how soon you are available. I've made my code protected agains this situation, w/o changing your pod.
