### ISSUE TITLE
Autoclosing tag parsing flow control design question?

### ISSUE THREAD

**Issue by jiyee** [nicolasgoutaland/GONMarkupParser#22]
I have one question about autocloing tag parsing flow control while I reading the source code recently.

In `parseString:error:` method, to determine the tag is autoclosing, then parse it seperately.

Why not replacing the autoclosing tag with the opening and closing tag pair before call `parseString:error:` method. If this, the parsing flow control will become more consistent.

**Comment by nicolasgoutaland** [comment]
Hi,

If I understand, you are suggesting to modify parsed string, replacing autoclosing tags by their counterparts ? It is not a good practice to update input data before parsing it. Then, doing such search / replace can lead to inconsistent document. If base string is malformed for example, with problem in open / close tags balance, the output may differ from original one.

Regards,

**Comment by jiyee** [comment]
thx.
