### ISSUE TITLE
Using in Swift!!!?

### ISSUE THREAD

**Issue by reza-khalafi** [nicolasgoutaland/GONMarkupParser#24]
Hello
I want to using this component in swift language.
How? ....

**Comment by nicolasgoutaland** [comment]
Hi, I think there is no problem on using this library in a Swift project.
If so, feel free to tell me and I will fix it.
Regards

**Comment by jeremiasdsa** [comment]
Hi @nicolasgoutaland , I got it running in swift.
But I think that it is missing that tag : < strong > Some Text< / strong > . 
<strong> Some Text</strong> (using a strong tag).
[https://www.w3schools.com/tags/tag_strong.asp](url)

Can you give me direction of how to add strong tag in swift?

**Comment by nicolasgoutaland** [comment]
Hi,

The best way is to create a subclass of the "bold" markup tag and register it under "strong" markup.

Regards

**Comment by nicolasgoutaland** [comment]
Hi @jeremiasdsa 
Did just pushed a new release with support for the strong tag.
https://github.com/nicolasgoutaland/GONMarkupParser/releases/tag/0.7.5
Regards,

**Comment by jeremiasdsa** [comment]
Hi @nicolasgoutaland 
Thanks for your reply.

I'm using pod 'GONMarkupParser' to install it.
it didn't install using pod 'GONMarkupParser', '~> 0.7.5'
Also only using pod 'GONMarkupParser'  its install the 0.7.4 version.

best regards,

**Comment by jeremiasdsa** [comment]
Hi again @nicolasgoutaland 

Got the 0.7.5 using  :
`pod 'GONMarkupParser', :git => 'https://github.com/nicolasgoutaland/GONMarkupParser.git', :branch => 'master'`

instead `pod 'GONMarkupParser', '~> 0.7.5'`

And it is all working using Swift 3. 👍 
Regards,
