### ISSUE TITLE
Calculate Height Markedup Text

### ISSUE THREAD

**Issue by NeerajKumar123** [nicolasgoutaland/GONMarkupParser#25]
I have to find the height of below mention string. 
`
<b><font color='#565E6F'>Apollo Munich - Dengue Care<\/font><\/b><br><font color='#565E6F'>&emsp; Sum Insured : <\/font><b><font color='#565E6F'>&#8377; 50 K<\/font><\/b><br><font color='#565E6F'>&emsp; Premium : <\/font><b><font color='#565E6F'><b><font color='#565E6F'>&#8377;<\/font><\/b> 511<\/font><\/b><br><font color='#565E6F'>&emsp; Members : <\/font><b><font color='#565E6F'>All Members<\/font><\/b>`

**Comment by nicolasgoutaland** [comment]
Hi, I do not understand your question. I think you mean the height of the string once displayed in a UILabel ?
