### ISSUE TITLE
Markup Missing.

### ISSUE THREAD

**Issue by alph0x** [nicolasgoutaland/GONMarkupParser#26]
Hi, i just wanted to tell you that 'Strong' Markup is missing, i already added on my copy of this Lib, but you should consider it for further releases.

**Comment by nicolasgoutaland** [comment]
Thanks for your feedback, i will consider adding it.
Regards

**Comment by nicolasgoutaland** [comment]
Hi there.
Did just pushed a new release with support for the strong tag.
https://github.com/nicolasgoutaland/GONMarkupParser/releases/tag/0.7.5
Regards,
