### ISSUE TITLE
Adding line on UITextView

### ISSUE THREAD

**Issue by jeremiasdsa** [nicolasgoutaland/GONMarkupParser#27]
Hi @nicolasgoutaland ,

I'm looking for a function to insert text on a UITextView.
for example:
`textView.insert("<strong>house</strong>")`
`textView.insert("<blue>car</car>")`
This way I'm adding text dynamically istead of converting the whole text.
![image](https://user-images.githubusercontent.com/9071775/27160410-72d75644-514a-11e7-811c-0bd6a7ff6f25.png)

There is a way to do that? I only saw <strong>.setMarkedUpText(String)</strong> function. 
I'm looking for something like <strong>.insertMarkedUpText(String)</strong>.

**Comment by nicolasgoutaland** [comment]
Hi @jeremiasdsa .
You can achieve that by building your attributedString then setting it to your label.
Regards
