### ISSUE TITLE
The specification of `link_with` in the Podfile is now unsupported

### ISSUE THREAD

**Issue by JulesMoorhouse** [nicolasgoutaland/GONMarkupParser#28]
[!] Invalid `Podfile` file: [!] The specification of `link_with` in the Podfile is now unsupported, please use target blocks instead..

The demo needs an update to it's podfile

**Comment by JulesMoorhouse** [comment]
Think this should do it.. not sure about GONMarkupParserSampleTests

source 'https://github.com/CocoaPods/Specs.git'
#link_with 'GONMarkupParserSample', 'GONMarkupParserSampleTests'

platform :ios, '7.0'
#xcodeproj 'GONMarkupParserSample'

target :GONMarkupParserSample do
	pod 'NSString+Color'
	pod 'LazyProperty'
end

**Comment by nicolasgoutaland** [comment]
Thanks a lot ;)
Regards
