### ISSUE TITLE
Link support

### ISSUE THREAD

**Issue by andyfitter** [nicolasgoutaland/GONMarkupParser#3]
Hi,

I'm having trouble with your recent link support code. The demo doesn't appear to work on either of my test devices - An iOS 7 iPhone 5 and an iOS 8 iPhone 4S. The links are rendered but not selectable and the delegate is never called.

I've had slightly more luck porting the code into my own App - it seem to work on the iOS 8 device but the links are rendered but not selectable on my iOS 7 device.

Any ideas why that might be?

**Comment by nicolasgoutaland** [comment]
Hi,
Are you talking about the anchor sample, or the custom markups sample ?

**Comment by andyfitter** [comment]
Ah, sorry, I should have been more clear - Its the Anchor sample on the develop branch.

**Comment by nicolasgoutaland** [comment]
Ok. I've merged the develop in master this morning, but I didn't update the sample, my bad.
Working on it.

**Comment by nicolasgoutaland** [comment]
You can check the "Custom markups" sample, that should works.
To be sure that anchors tags are working, check that you are displaying your attributed string in a UITextView and that your delegate is correctly set.

**Comment by nicolasgoutaland** [comment]
Just pushed an updated sample. Let me know if everything is ok.

**Comment by andyfitter** [comment]
Thanks for that - The sample works fine now. Do you know of any reason that the Anchor code would not work on iOS 7.0? Both your sample app (If adjusted to allow iOS 7) and my code render the links fine, but the delegate method never gets called.

Andrew Fitter
andy@fittersystems.com

**Comment by nicolasgoutaland** [comment]
This is strange. I have no problem on an iOS 7.1 simulator. Cannot test under iOS7.0 for now.

Are you using Interface Builder to configure your UITextView, or did you configure it by code ?
Have you tried following :
- implement other delegate methods, and check if they are called or not
- set the delegate manually
- set UITextView configuration manually

```
     _resultTextView.editable   = NO;
    _resultTextView.selectable = YES;
```

Let me know if it solves your problem.

**Comment by andyfitter** [comment]
Hi. Sorry if I wasn't clear - 7,1 and 8.x work fine, but 7.0 doesn't work. I wondered if you knew any reason why 7.1 would work but not 7.0

I might be able to change the app to support 7.1 upwards and all will be ok. 

Thanks.

**Comment by nicolasgoutaland** [comment]
Ok. Did you try to implements other delegate methods ? Are they called ? 
Have you tried to configure your textview editable / selectable / delegate properties by code ?
This is the only reason I could find, that xib might by misinterpreted.

**Comment by nicolasgoutaland** [comment]
Seems to be a problem with NSTextAttachment in iOS 7.0.
Working on a fix.

**Comment by andyfitter** [comment]
Great, thanks.

Andrew Fitter
andy@fittersystems.com

**Comment by nicolasgoutaland** [comment]
Just pushed a fix in the develop branch. Can you try the sample on iOS 7.0 ?

If my guess is correct, the delegate method to implement is `- (BOOL)textView:(UITextView *)textView shouldInteractWithURL:(NSURL *)URL inRange:(NSRange)characterRange`now.

**Comment by andyfitter** [comment]
Seems to work ok on all my test devices - iOS 7.0 and upwards

Andrew Fitter
andy@fittersystems.com

**Comment by nicolasgoutaland** [comment]
Great, Merging it to master, updating Pod and Doc.
Thanks for the bug report.
