### ISSUE TITLE
Is GONMarkupParser can render an html like this one?

### ISSUE THREAD

**Issue by TofPlay** [nicolasgoutaland/GONMarkupParser#5]
Hi,
Is GONMarkupParser can render an html like this one?

``` html
<html>
    <head>
        <style>
        h2 {
        font-family: 'OpenSans';
        font-size: 19;
        }

        p {
        font-family: 'OpenSans';
        font-size: 14;
        }

        u {
        font-family: 'OpenSans';
        font-size: 14;
        text-decoration: 'underline';
        }

        em {
        font-family: 'OpenSans-Italic';
        font-size: 14;
        }

        code {
        font-family: 'OpenSans-Light';
        font-size: 14;
        }

        h3 {
        font-family: 'OpenSans';
        font-size: 16;
        }

        div {
        font-family: 'OpenSans';
        font-size: 14;
        }

        span {
        font-family: 'OpenSans';
        font-size: 14;
        }

        h1 {
        font-family: 'OpenSans';
        font-size: 21;
        }

        b {
        font-family: 'OpenSans-Bold';
        font-size: 14;
        }
        </style>
    </head>
    <body>
        <h1>Titre 1</h1>
        <h2>Titre 2</h2>
        <h3>Titre 3</h3>
        <p>
            <strong>gras</strong><br/>
            <em>italic</em><br/>
            <u>underscore</u>
        </p>
        <p><code>ruby
            require 'redcarpet'
            markdown = Redcarpet.new("Hello World!")
            puts markdown.to_html
        </code></p>
        <p>This is a text</p>
        <p>An image</p>
        <p>
            <a href="http://www.houstonpettalk.com/wp-content/uploads/2009/04/grass.jpg"><img src="http://www.houstonpettalk.com/wp-content/uploads/2009/04/grass.jpg" height="156" width="218" alt="grass.jpg" /></a>
        </p>
        <p>A video</p>
        <video height="150" width="218" controls>
            <source src="http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4" type="video/mp4"> Your browser does not support the video tag.
        </video>
    </body>
</html>
```

**Comment by nicolasgoutaland** [comment]
Hi,
unfortunately this is not the purpose of the GONMarkupParser to interpret plain HTML.
It's purpose is to provide a syntaxe to generate NSAttributedString.

Regards,

**Comment by TofPlay** [comment]
@nicolasgoutaland my html is very simple. No include, no javascript. Just basic embedded css, basic tags, links, images and html5 video. Your component already support basic tags. Links and images are supported by NSAttributedString. I believe that only the video that is not natively supported by NSAttributedString. You are not very far to support my html. :smile:

**Comment by nicolasgoutaland** [comment]
You are right, but the parser will never handle CSS, this is not the objective ;)
And video tag is a nonsense in an AttributedString :)

**Comment by nicolasgoutaland** [comment]
To be fair, I think an evolution could be to generate a parser using a given CSS configuration, using the "Style" tag as a special marker, but this will imply to let a markup update its parent object, the parser, which is not a good thing I think.
The current architecture of the Parser won't allow that, and since everything is based on a FIFO list, this won't work.
Perhaps a solution will be to strip the head section from your html, extract the style content and use it as a parameter to build generate a parser.
