### ISSUE TITLE
(Cocoa pods 0.39.0) "file not found with <angled> include use quotes instead" for "NSString+Color.h"

### ISSUE THREAD

**Issue by diegomontoyas** [nicolasgoutaland/GONMarkupParser#9]
Changing manually #import <NSString+Color.h> to #import "NSString+Color.h" solves the issue.

**Comment by nicolasgoutaland** [comment]
hum, very strange. I am using 0.39 too, and do not have any problem. Are you sure you are not overriding Library / headers search path elsewhere ?

**Comment by diegomontoyas** [comment]
Thanks for the response Nicolas, what should I look for exactly in my header/library search settings? I saw this response from 'rota' at CocoPods:

> In simplified: angled bracket imports are for externals, and should be scoped according to where they come from, so this for example should be:
> 
> `#import <RXCollection/RXCollection.h>`
> 
> So that the compiler knows where to link correctly. I'm not sure what's changed in CP, but we shouldn't have been supporting #import <RXCollection.h> as it breaks the compiler contract.

So from this I understand it should be something like
`#import <NSString+Color/NSString+Color.h>`
or
`#import "NSString+Color.h"` 
but I could be wrong.

Saw this thread as well 
[Cocoapods 0.38.2: error: 'Mixpanel.h' file not found with <angled> include; use "quotes" instead](https://github.com/segmentio/analytics-ios/issues/417)
